repos:
  - repo: local
    hooks:
      - id: csharpier-check
        name: csharpier check
        entry: scripts/lint.sh
        language: system
        pass_filenames: false
      - id: csharpier-format
        name: csharpier format
        entry: scripts/format.sh
        language: system
        pass_filenames: false
      - id: dotnet-test
        name: dotnet test
        entry: scripts/test.sh
        language: system
        pass_filenames: false
